services:
  app:
    build: .
    container_name: tkb
    depends_on:
      - postgres
      - chroma
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: app_db
    ports:
      - "5431:5432"   # host:container
    volumes:
      - postgres_data:/var/lib/postgresql/data

  chroma:
    image: chromadb/chroma:latest
    container_name: chroma
    restart: always
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/data

volumes:
  postgres_data:
  chroma_data:
